// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGrVoAGUGT9fPfavjpFz4BVqlmXat503Y',
    appId: '1:344256821707:ios:8e393caa98d9e0778ade4e',
    messagingSenderId: '344256821707',
    projectId: 'prime-status-1db09',
    storageBucket: 'prime-status-1db09.firebasestorage.app',
    iosBundleId: 'com.aksmlibts.primestatus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGkRvNqYwz0B8HoRqqFMI0-wu-nvkVgpE',
    appId: '1:344256821707:web:5e7fe5c7d7b414308ade4e',
    messagingSenderId: '344256821707',
    projectId: 'prime-status-1db09',
    authDomain: 'prime-status-1db09.firebaseapp.com',
    storageBucket: 'prime-status-1db09.firebasestorage.app',
    measurementId: 'G-XKV0NY6S12',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkRvNqYwz0B8HoRqqFMI0-wu-nvkVgpE',
    appId: '1:344256821707:web:53e2616dd13f2a148ade4e',
    messagingSenderId: '344256821707',
    projectId: 'prime-status-1db09',
    authDomain: 'prime-status-1db09.firebaseapp.com',
    storageBucket: 'prime-status-1db09.firebasestorage.app',
    measurementId: 'G-3TJM8TW7N2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGrVoAGUGT9fPfavjpFz4BVqlmXat503Y',
    appId: '1:344256821707:ios:8e393caa98d9e0778ade4e',
    messagingSenderId: '344256821707',
    projectId: 'prime-status-1db09',
    storageBucket: 'prime-status-1db09.firebasestorage.app',
    iosBundleId: 'com.aksmlibts.primestatus',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwnSiHV5mmT0rscA47TcwRlJjU6mmwWSk',
    appId: '1:344256821707:android:3aaba441c4ce80428ade4e',
    messagingSenderId: '344256821707',
    projectId: 'prime-status-1db09',
    storageBucket: 'prime-status-1db09.firebasestorage.app',
  );

}